bootstrap:
  theme: paper

dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.68.99.100:5432/exorigo
  username: exorigo
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: false